// examples/react/components/App.js
import React, { Component } from 'react'
import LangSelect from './LangSelect'
import t from '../../t'

class App extends Component {

  componentDidMount () {
    console.log(
      t(
        '欢迎来到中国',
        'Welcome to the US',
        'ようこそ日本へ'
      )
    )
  }

  render () {
    return (
      <div>
        <LangSelect />

        { t(
          '你好，世界',
          'Hello, world',
          'こんにちは、世界'
        ) }
      </div>
    )
  }

}

export default App

// examples/vue/components/App.vue
<template>
  <div>
    <lang-select />

    {{ $t(
      '你好，世界',
      'Hello, world',
      'こんにちは、世界'
    ) }}
  </div>
</template>
<script>
import LangSelect from './LangSelect'

export default {
  components: { LangSelect },
  mounted () {
    console.log(
      this.$t(
        '欢迎来到中国',
        'Welcome to the US',
        'ようこそ日本へ'
      )
    )
  }
}
</script>
